language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - sudo apt-get install python3-matplotlib
env:
    - TEST_DIR=code 
script:
    - cd $TEST_DIR && py.test
after_success:
    - coveralls
