language: python
python:
    - "3.5"
install:
    - pip install --use-mirrors matplotlib
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
env:
    - TEST_DIR=code
script:
    - cd $TEST_DIR && py.test
after_success:
    - coveralls
