language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
env:
    - $TEST = code
script:
    - cd $TEST && py.test
after_success:
    - coveralls
