language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
env:
    - TEST_DIR=code
    - TEST_DIR=code/test_xmls
script:
    - cd $TEST_DIR && py.test
after_success:
    - coveralls
